version: "3.9"

services:
 myapp:
   image: jsnchzjmnz/myapp:latest
   ports:
     - 5000:5000
   environment:
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: mypassword
     POSTGRES_DB: myappdb
     POSTGRES_HOST: mypostgres
     POSTGRES_PORT: 5432

 db:
   image: jsnchzjmnz/postgres:latest
   hostname: mypostgres
   ports:
     - 5432:5432
   environment:
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: mypassword
