version: "3"

services:
  myapp:
    image: app
    ports:
      - 5000:5000
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myappdb
      POSTGRES_HOST: mypostgres
      POSTGRES_PORT: 5432

  db:
    image: postgres
    hostname: mypostgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
